"""Initial migration: Current schema

Revision ID: 871c4edfd303
Revises: 
Create Date: 2026-04-12 20:07:24.531536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871c4edfd303'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folder')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'folder_id')
    op.create_foreign_key(None, 'processing_task', 'video_template', ['video_template_id'], ['id'])
    op.create_foreign_key(None, 'processing_task', 'doctor_info', ['doctor_info_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processing_task', type_='foreignkey')
    op.drop_constraint(None, 'processing_task', type_='foreignkey')
    op.add_column('file', sa.Column('folder_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'file', 'folder', ['folder_id'], ['id'])
    op.create_table('folder',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('color', sa.VARCHAR(length=20), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
